// src/api/youtube.js
// Fetches YouTube transcript server-side — mirrors the robust multi-fallback
// system from ThunderStudy Flashcards (youtube-transcript.js).
//
// Why multi-fallback: hitting YouTube's Innertube API directly from a cloud
// IP (Cloudflare, Vercel, Render, etc.) gets blocked. Instead we chain through reliable
// 3rd-party transcript services in order, falling through on failure:
//
//   1. youtube-transcript.ai   — free hosted service, no key
//   2. youtube-transcriber-api — community Vercel-hosted Python/jdepoix wrapper
//   3. youtube-transcript-api-tau-one — community Vercel-hosted wrapper
//   4. youtube-transcript-plus (npm) — direct-to-YouTube
//
// All four are raced IN PARALLEL and the first usable transcript wins (the rest are
// aborted). Every source has a hard timeout, so one hung/dead service can never eat the
// whole request budget and turn into an HTML gateway error the browser can't parse.
//
// Request:  POST { videoId: "11-char-id" }
// Response: 200 { title, transcript, language?, isAutoGenerated?, warning? }
//           4xx/5xx { error }

import { json, guard, readBody } from '../util.js';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// Per-source deadline, tied to a shared "winner found" controller: the moment one source
// succeeds every other in-flight request is cancelled and its timer cleared.
function makeSignal(ms, parent) {
  const c = new AbortController();
  const t = setTimeout(() => c.abort(new Error(`timed out after ${ms}ms`)), ms);
  c.signal.addEventListener('abort', () => clearTimeout(t), { once: true });
  if (parent) {
    if (parent.aborted) c.abort(parent.reason);
    else parent.addEventListener('abort', () => c.abort(parent.reason), { once: true });
  }
  return c.signal;
}

// Some free transcript services answer with HTTP 200 and a plain-text "you are rate limited /
// buy a plan" message instead of a transcript. That used to be accepted as the transcript
// (it is long enough), so the test was generated from an advert. Reject those outright so the
// race moves on to the next source.
const JUNK_RE = /(high volume|rate[- ]?limit|too many requests|partnership plan|commercial\s*\/|support it properly|@youtube-transcript\.ai|upgrade (your )?plan|api[- ]?key (is )?(required|missing|invalid)|quota (exceeded|reached)|access denied|captcha)/i;
function assertRealTranscript(text, source) {
  if (text.length < 50) throw new Error(`${source} returned empty/short text`);
  // A genuine transcript is long; the junk messages are a few hundred characters at most.
  if (text.length < 1500 && JUNK_RE.test(text)) throw new Error(`${source} returned a service message, not a transcript`);
  if (/^\s*<(!doctype|html)/i.test(text)) throw new Error(`${source} returned an HTML page`);
  return text;
}

// ── Source 1: youtube-transcript.ai ─────────────────────────────────────────
// Returns Markdown with YAML front-matter + "[m:ss] line" transcript.
async function tryYoutubeTranscriptAi(videoId, parent) {
  const res = await fetch(
    `https://youtube-transcript.ai/transcript/${encodeURIComponent(videoId)}.txt`,
    {
      headers: {
        'User-Agent': 'ThunderStudyAiMock/1.0 (transcript-fetch)',
        'Accept': 'text/plain, text/markdown, */*'
      },
      signal: makeSignal(10000, parent)
    }
  );
  if (!res.ok) throw new Error(`youtube-transcript.ai status ${res.status}`);

  let text = await res.text();
  text = text.replace(/^\s*---\s*\n[\s\S]*?\n---\s*/, '');   // strip YAML front-matter (only at the very top)
  text = text.replace(/\[(?:\d+:)?\d+:\d+\]/g, '');        // strip [m:ss] AND [h:mm:ss] timestamps (long videos)
  text = text.replace(/\n{3,}/g, '\n\n').trim();

  assertRealTranscript(text, 'youtube-transcript.ai');
  return { text };
}

// ── Source 2: youtube-transcriber-api.vercel.app (community, Python/jdepoix) ─
async function tryMongjFallback(videoId, parent) {
  const res = await fetch(
    `https://youtube-transcriber-api.vercel.app/v1/transcripts?id=${encodeURIComponent(videoId)}&type=text&lang=en`,
    { headers: { 'User-Agent': 'ThunderStudyAiMock/1.0' }, signal: makeSignal(10000, parent) }
  );
  if (!res.ok) throw new Error(`mongj fallback status ${res.status}`);

  const data = await res.json();
  const transcripts = Array.isArray(data.transcripts) ? data.transcripts : [];
  const text = (transcripts[0]?.text || '').trim();
  assertRealTranscript(text, 'youtube-transcriber-api');
  return { text };
}

// ── Source 3: youtube-transcript-api-tau-one.vercel.app (community) ─────────
async function tryJaypaunFallback(videoId, parent) {
  const res = await fetch('https://youtube-transcript-api-tau-one.vercel.app/transcript', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'ThunderStudyAiMock/1.0'
    },
    body: JSON.stringify({ video_url: `https://www.youtube.com/watch?v=${videoId}` }),
    signal: makeSignal(10000, parent)
  });
  if (!res.ok) throw new Error(`jaypaun fallback status ${res.status}`);

  const data = await res.json();
  const text = (data.transcript || '').trim();
  assertRealTranscript(text, 'youtube-transcript-api-tau');
  return { text };
}

// ── Source 4: youtube-transcript-plus (npm, direct to YouTube) ───────────────
// Needs no third party to be alive, but can get blocked on a cloud IP — hence the race.
// Loaded with a dynamic import() so a failure to load/run it only fails this one source.
async function tryYoutubeTranscriptPlus(videoId, parent) {
  const { fetchTranscript } = await import('youtube-transcript-plus');
  const result = await fetchTranscript(videoId, {
    userAgent: UA,
    retries: 1,
    retryDelay: 500,
    signal: makeSignal(15000, parent)
  });
  const segments = Array.isArray(result) ? result : result?.segments;
  if (!segments || segments.length === 0)
    throw new Error('youtube-transcript-plus returned no segments');

  const text = segments.map(s => s.text).join(' ').replace(/\s+/g, ' ').trim();
  assertRealTranscript(text, 'youtube-transcript-plus');
  return { text, segmentCount: segments.length, isAutoGenerated: true };
}

// Turn the direct-to-YouTube library's typed error into a specific message.
// Returns null when the error is generic (network, timeout, parse, …).
function friendlyYoutubeError(err) {
  switch (err && err.name) {
    case 'YoutubeTranscriptDisabledError':
    case 'YoutubeTranscriptNotAvailableError':
      return 'No captions could be found for this video (it may not have subtitles, or YouTube blocked the request).';
    case 'YoutubeTranscriptVideoUnavailableError':
      return 'That video is unavailable (private, removed, or region/age-restricted).';
    case 'YoutubeTranscriptTooManyRequestError':
      return 'YouTube is rate-limiting the server right now — wait a minute and try again.';
    default:
      return null;
  }
}

export default async function handler(request) {
  const early = guard(request);
  if (early) return early;

  const { videoId } = await readBody(request);

  if (!videoId || typeof videoId !== 'string' || !/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    return json({ error: 'Invalid videoId' }, 400);
  }

  const sources = [
    { name: 'youtube-transcript.ai',      run: tryYoutubeTranscriptAi },
    { name: 'youtube-transcriber-api',    run: tryMongjFallback       },
    { name: 'youtube-transcript-api-tau', run: tryJaypaunFallback     },
    { name: 'youtube-transcript-plus',    run: tryYoutubeTranscriptPlus },
  ];

  // Race all sources; first usable transcript wins, then the rest are aborted.
  const winner = new AbortController();
  const failures = [];
  let result = null;
  try {
    result = await Promise.any(sources.map(async (source) => {
      try {
        const out = await source.run(videoId, winner.signal);
        return { name: source.name, ...out };
      } catch (err) {
        if (!winner.signal.aborted) {   // don't log the losers we cancelled ourselves
          console.warn(`[youtube] ${source.name} failed:`, err && err.message);
          failures.push({ name: source.name, err });
        }
        throw err;
      }
    }));
  } catch (_aggregate) {
    // every source failed — handled below
  } finally {
    winner.abort(); // cancel losers + clear their timers
  }

  if (result) {
    const transcript = result.text.slice(0, 20000);
    console.log(`[youtube] success via ${result.name}, chars=${transcript.length}`);
    return json({
      title: '',         // fallback sources don't return title; frontend handles gracefully
      transcript,
      language: 'en',
      isAutoGenerated: !!result.isAutoGenerated,
      ...(result.segmentCount ? { segmentCount: result.segmentCount } : {})
    });
  }

  // All sources exhausted — return graceful empty so the frontend still works.
  // Prefer the specific reason from the direct-to-YouTube library when it has one.
  const direct = failures.find(f => f.name === 'youtube-transcript-plus');
  const reason = (direct && friendlyYoutubeError(direct.err)) ||
    'Could not fetch a transcript. The video may have no captions, or may be private/age-restricted.';
  return json({
    title: '',
    transcript: '',
    warning: reason + ' Paste the transcript into the Additional Context box, or generate from the topic only.'
  });
}
